/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDevice {
    }
    interface AppDonor {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppLocation {
    }
    interface AppLogin {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRegister {
    }
    interface AppRoot {
    }
    interface AppSchool {
    }
    interface AppSchoolList {
    }
    interface AppSchoolRegister {
    }
    interface AppStudent {
    }
    interface AppVoluntary {
    }
    interface PageHome {
    }
}
declare global {
    interface HTMLAppDeviceElement extends Components.AppDevice, HTMLStencilElement {
    }
    var HTMLAppDeviceElement: {
        prototype: HTMLAppDeviceElement;
        new (): HTMLAppDeviceElement;
    };
    interface HTMLAppDonorElement extends Components.AppDonor, HTMLStencilElement {
    }
    var HTMLAppDonorElement: {
        prototype: HTMLAppDonorElement;
        new (): HTMLAppDonorElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLocationElement extends Components.AppLocation, HTMLStencilElement {
    }
    var HTMLAppLocationElement: {
        prototype: HTMLAppLocationElement;
        new (): HTMLAppLocationElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRegisterElement extends Components.AppRegister, HTMLStencilElement {
    }
    var HTMLAppRegisterElement: {
        prototype: HTMLAppRegisterElement;
        new (): HTMLAppRegisterElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSchoolElement extends Components.AppSchool, HTMLStencilElement {
    }
    var HTMLAppSchoolElement: {
        prototype: HTMLAppSchoolElement;
        new (): HTMLAppSchoolElement;
    };
    interface HTMLAppSchoolListElement extends Components.AppSchoolList, HTMLStencilElement {
    }
    var HTMLAppSchoolListElement: {
        prototype: HTMLAppSchoolListElement;
        new (): HTMLAppSchoolListElement;
    };
    interface HTMLAppSchoolRegisterElement extends Components.AppSchoolRegister, HTMLStencilElement {
    }
    var HTMLAppSchoolRegisterElement: {
        prototype: HTMLAppSchoolRegisterElement;
        new (): HTMLAppSchoolRegisterElement;
    };
    interface HTMLAppStudentElement extends Components.AppStudent, HTMLStencilElement {
    }
    var HTMLAppStudentElement: {
        prototype: HTMLAppStudentElement;
        new (): HTMLAppStudentElement;
    };
    interface HTMLAppVoluntaryElement extends Components.AppVoluntary, HTMLStencilElement {
    }
    var HTMLAppVoluntaryElement: {
        prototype: HTMLAppVoluntaryElement;
        new (): HTMLAppVoluntaryElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLElementTagNameMap {
        "app-device": HTMLAppDeviceElement;
        "app-donor": HTMLAppDonorElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-location": HTMLAppLocationElement;
        "app-login": HTMLAppLoginElement;
        "app-menu": HTMLAppMenuElement;
        "app-profile": HTMLAppProfileElement;
        "app-register": HTMLAppRegisterElement;
        "app-root": HTMLAppRootElement;
        "app-school": HTMLAppSchoolElement;
        "app-school-list": HTMLAppSchoolListElement;
        "app-school-register": HTMLAppSchoolRegisterElement;
        "app-student": HTMLAppStudentElement;
        "app-voluntary": HTMLAppVoluntaryElement;
        "page-home": HTMLPageHomeElement;
    }
}
declare namespace LocalJSX {
    interface AppDevice {
    }
    interface AppDonor {
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppLocation {
    }
    interface AppLogin {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRegister {
    }
    interface AppRoot {
    }
    interface AppSchool {
    }
    interface AppSchoolList {
    }
    interface AppSchoolRegister {
    }
    interface AppStudent {
    }
    interface AppVoluntary {
    }
    interface PageHome {
    }
    interface IntrinsicElements {
        "app-device": AppDevice;
        "app-donor": AppDonor;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-location": AppLocation;
        "app-login": AppLogin;
        "app-menu": AppMenu;
        "app-profile": AppProfile;
        "app-register": AppRegister;
        "app-root": AppRoot;
        "app-school": AppSchool;
        "app-school-list": AppSchoolList;
        "app-school-register": AppSchoolRegister;
        "app-student": AppStudent;
        "app-voluntary": AppVoluntary;
        "page-home": PageHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-device": LocalJSX.AppDevice & JSXBase.HTMLAttributes<HTMLAppDeviceElement>;
            "app-donor": LocalJSX.AppDonor & JSXBase.HTMLAttributes<HTMLAppDonorElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-location": LocalJSX.AppLocation & JSXBase.HTMLAttributes<HTMLAppLocationElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-register": LocalJSX.AppRegister & JSXBase.HTMLAttributes<HTMLAppRegisterElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-school": LocalJSX.AppSchool & JSXBase.HTMLAttributes<HTMLAppSchoolElement>;
            "app-school-list": LocalJSX.AppSchoolList & JSXBase.HTMLAttributes<HTMLAppSchoolListElement>;
            "app-school-register": LocalJSX.AppSchoolRegister & JSXBase.HTMLAttributes<HTMLAppSchoolRegisterElement>;
            "app-student": LocalJSX.AppStudent & JSXBase.HTMLAttributes<HTMLAppStudentElement>;
            "app-voluntary": LocalJSX.AppVoluntary & JSXBase.HTMLAttributes<HTMLAppVoluntaryElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
        }
    }
}
